server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/spring-cloud-gateway-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/spring-cloud-gateway-realm
      client:
        registration:
          keycloak:
            client-id: spring-cloud-gateway-client
            client-secret: 05f68c36-9c95-4e5b-bb3f-031a25325c23
            clientName: spring-cloud-gateway-client
            authorization-grant-type: authorization_code
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/auth/realms/spring-cloud-gateway-realm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/spring-cloud-gateway-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/spring-cloud-gateway-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/auth/realms/spring-cloud-gateway-realm/protocol/openid-connect/certs
            user-name-attribute: preferred_username


  cloud:
    #    loadbalancer:
    #      ribbon:
    #        enabled: false
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        #        - id: eureka-server
        #          uri: http://localhost:8761/health
        #          predicates:
        #            - Path=/health**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: user-management-service
          uri: lb://user-management-service/  # switch 'lb://' to 'http://'    lb://user-management-service/  on kubernetes error occur try user http:// if local error occur try lb://
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/

# ---
#  spring:
#    config:
#      activate:
#        on-cloud-platform: kubernetes
#    cloud:
#      kubernetes:
#        enabled: true

#  eureka:
#    client:
#      enabled: false
