# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     serviceUrl:
#       defaultZone: http://discUser:discPassword@localhost:8761/eureka
#   instance:
#     hostname: localhost

management:
  endpoint:
    restart:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    kubernetes:
      loadbalancer:
        enabled: false
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     prefer-ip-address: true
#     hostname: localhost

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
  cloud:
    kubernetes:
      enabled: true

eureka:
  client:
    enabled: false
