server:
  port: 8761
  servlet:
    context-path: /eureka/

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: eureka-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/spring-cloud-gateway-realm
